---
name: List-Parseable
version: 1.03
author:
  - 'Sullivan Beck <sbeck@cpan.org>'
abstract: routines to work with lists containing a simple language
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Sort::DataTypes: 0
  Storable: 0
  Text::Balanced: 0
  perl: 5.6.0
build_requires:
  Test::More: 0
provides:
  List::Parseable:
    file: lib/List/Parseable.pm
    version: 1.03
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
