---
abstract: 'routines to work with lists containing a simple language'
author:
  - 'Sullivan Beck <sbeck@cpan.org>'
build_requires:
  Test::Inter: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: List-Parseable
provides:
  List::Parseable:
    file: lib/List/Parseable.pm
    version: 1.06
requires:
  Sort::DataTypes: 3.00
  Storable: 0
  Text::Balanced: 0
  perl: 5.000
resources:
  license: http://dev.perl.org/licenses/
version: 1.06
